# -*- coding: utf-8 -*-
"""14_run_roberta_test_inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-5Jx-JelbNx6HfmIbIFuJsVL6wmaZ_xg
"""

"""
==============================================================
MASTER THESIS

RoBERTa Final Test-Set Inference

==============================================================
"""

import time
from pathlib import Path

import numpy as np
import pandas as pd
import torch

from tqdm.auto import tqdm
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification
)

# ============================================================
# PATHS
# ============================================================

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = PROJECT_ROOT / "data"
OUTPUT_DIR = PROJECT_ROOT / "results" / "roberta"

MODEL_PATH = OUTPUT_DIR / "best_roberta"
INPUT_FILE = DATA_DIR / "modeling_test.csv"

OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

PREDICTION_FILE = (
    OUTPUT_DIR /
    "roberta_test_predictions.csv"
)

SUMMARY_FILE = (
    OUTPUT_DIR /
    "roberta_test_inference_summary.txt"
)

# ============================================================
# SETTINGS
# ============================================================

MAX_LENGTH = 128
BATCH_SIZE = 32

# ============================================================
# LOAD TEST DATA
# ============================================================

print("=" * 70)
print("Loading final test dataset...")
print("=" * 70)

if not INPUT_FILE.exists():

    raise FileNotFoundError(
        f"Test dataset not found: {INPUT_FILE}"
    )

test_df = pd.read_csv(INPUT_FILE)

required_columns = {
    "tweet",
    "binary_hate_label_name",
    "dialect_group"
}

missing_columns = (
    required_columns -
    set(test_df.columns)
)

if missing_columns:

    raise ValueError(
        f"Missing required columns: {missing_columns}"
    )

print(f"Test rows: {len(test_df)}")

print("\nTrue-label distribution:")
print(
    test_df[
        "binary_hate_label_name"
    ].value_counts()
)

print("\nDialect distribution:")
print(
    test_df[
        "dialect_group"
    ].value_counts()
)

# ============================================================
# SANITY CHECK
# ============================================================

if len(test_df) != 3717:

    raise ValueError(
        f"Expected 3717 test rows, found {len(test_df)}"
    )

# ============================================================
# LOAD MODEL
# ============================================================

print("\n" + "=" * 70)
print("Loading trained RoBERTa model...")
print("=" * 70)

if not MODEL_PATH.exists():

    raise FileNotFoundError(
        f"Model directory not found: {MODEL_PATH}"
    )

tokenizer = AutoTokenizer.from_pretrained(
    MODEL_PATH
)

model = (
    AutoModelForSequenceClassification
    .from_pretrained(MODEL_PATH)
)

device = torch.device(
    "cuda"
    if torch.cuda.is_available()
    else "cpu"
)

model.to(device)
model.eval()

print(f"Device: {device}")

# ============================================================
# RUN BATCH INFERENCE
# ============================================================

texts = (
    test_df["tweet"]
    .fillna("")
    .astype(str)
    .tolist()
)

predicted_ids = []
hate_probabilities = []
prediction_confidences = []

start_time = time.time()

print("\n" + "=" * 70)
print("Running inference on the final test set...")
print("=" * 70)

for start in tqdm(
    range(0, len(texts), BATCH_SIZE)
):

    batch_texts = texts[
        start:start + BATCH_SIZE
    ]

    encoded = tokenizer(
        batch_texts,
        padding=True,
        truncation=True,
        max_length=MAX_LENGTH,
        return_tensors="pt"
    )

    encoded = {
        key: value.to(device)
        for key, value in encoded.items()
    }

    with torch.no_grad():

        outputs = model(**encoded)

        probabilities = torch.softmax(
            outputs.logits,
            dim=-1
        )

    batch_predictions = (
        probabilities.argmax(dim=-1)
        .cpu()
        .numpy()
    )

    batch_probabilities = (
        probabilities
        .cpu()
        .numpy()
    )

    predicted_ids.extend(
        batch_predictions.tolist()
    )

    hate_probabilities.extend(
        batch_probabilities[:, 1].tolist()
    )

    prediction_confidences.extend(
        batch_probabilities.max(axis=1).tolist()
    )

elapsed_time = time.time() - start_time

# ============================================================
# CREATE OUTPUT
# ============================================================

predictions_df = test_df.copy()

predictions_df[
    "predicted_label"
] = np.where(
    np.array(predicted_ids) == 1,
    "hate",
    "not_hate"
)

predictions_df[
    "hate_probability"
] = hate_probabilities

predictions_df[
    "prediction_probability"
] = prediction_confidences

predictions_df.to_csv(
    PREDICTION_FILE,
    index=False
)

# ============================================================
# SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("TEST INFERENCE COMPLETED")
print("=" * 70)

print(f"Rows predicted : {len(predictions_df)}")
print(f"Runtime seconds: {elapsed_time:.2f}")

print("\nPrediction distribution:")
print(
    predictions_df[
        "predicted_label"
    ].value_counts()
)

print(f"\nSaved to:\n{PREDICTION_FILE}")

with open(
    SUMMARY_FILE,
    "w",
    encoding="utf-8"
) as file:

    file.write(
        "RoBERTa Final Test-Set Inference\n"
    )

    file.write("=" * 70 + "\n\n")

    file.write(
        f"Test samples: {len(predictions_df)}\n"
    )

    file.write(
        f"Runtime seconds: {elapsed_time:.2f}\n\n"
    )

    file.write(
        "Prediction distribution:\n"
    )

    file.write(
        predictions_df[
            "predicted_label"
        ].value_counts().to_string()
    )

    file.write("\n")

